http://localhost:3000/test

###
http://localhost:3000/movies

###
http://localhost:3000/movies/5b2867455dacd427955611ed

###
POST http://localhost:3000/movies
Content-type: application/json

{
    "title": "Wonder Woman",
    "yearReleased": 2017,
    "rating": { "code": "PG", "description": "Parent's Guidance" },
    "comments": [
        { "body": "This is a great movie" },
        { "body": "This is a terrible movie" }
    ],
    "director": "5b29b3ece288909215ca20eb"
}