http://localhost:3000/test

###

http://localhost:3000/movies

###

http://localhost:3000/movies/5b2867455dacd427955611ed

###

http://localhost:3000/movies

{
    title: 'New Movie',
    yearReleased: 2018
}